version: "3.3"

services:
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8081:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://greenphyl:hades2000@gbjhvice075.eame.syngenta.org:2010/funphyl
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      #- HASURA_GRAPHQL_ADMIN_SECRET=shadyLady
    networks:
      network:

  pgadmin:
    container_name: ui
    image: dpage/pgadmin4
    environment:
      PGADMIN_LISTEN_PORT: 1111
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    depends_on:
      - hasura
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "1111:1111"
    networks:
      network:
    logging:
      driver: none

  # csv-writer:
  #   container_name: csv-writer
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/usr/src/app
  #     - ./node_modules:/usr/src/app/node_modules
  #   env_file:
  #     - ./src/etc/.env
  #   depends_on:
  #     - hasura
  #   networks:
  #     network:

networks:
  network:
volumes:
  volume:
