resolvers:
  - name: person_csv
    resolver_target: csv
    fields:
      - arg: address
        type: string
      - arg: name
        type: string
  - name: giraffe_csv
    resolver_target: csv
    fields:
      - arg: neck_size
        type: integer
      - arg: eyeball_size
        type: float
