resolvers:
  - name: person-csv
    resolver_target: csv
    fields:
      - arg: age
        type: integer
      - arg: name
        type: string
  - name: giraffe-csv
    resolver_target: csv
    fields:
      - arg: eye_colour
        type: integer
      - arg: neck_length
        type: float