resolvers:
  - name: family_csv
    resolver_target: csv
    fields:
      - arg: level
        type: integer
      - arg: name
        type: string
  - name: taxon_csv
    resolver_target: csv
    fields:
      - arg: scientific_name
        type: string
      - arg: rank
        type: string
